### ISSUE TITLE
how to run the makefile command file

### ISSUE THREAD

**Issue by icebird28** [kevinquillen/metaquake#15]
i read the installation instructions and am unable to figure out how to use the makefile to build the files for the meta directory.  can you help?

**Comment by kevinquillen** [comment]
If you just want to have the mod, you can grab the built release from the [Releases page (.tar.gz)](https://github.com/kevinquillen/metaquake/releases).

If you want to modify and build locally, you can use `make progs.dat` for the Quake client or `make qwprogs.dat` for QuakeWorld using Make. I made some changes that assume that the developer has bash, Make, and is building in an Linux or Linux like environment (cp, tar, etc commands available).

You will notice each command calls $(QCC) first - if qccx is not building correctly, none of the others are going to work.

**Comment by icebird28** [comment]
I downloaded the .tar file.  I don't plan on making changes to it, just want to play it.  Do I need to run the makefile at all?  or just unzip to the nquake directory?  i apologize for being a dumb-ass.  I've never run quake mods on my own, it was always someone else doing it.

**Comment by kevinquillen** [comment]
No, you only need to build it from source if you want to make changes. Otherwise, the tar file has what you need. You can untar that and put the `meta` directory in the nquakesv root directory.

The Release page will always have the latest release + built source in the tar file, you only need the tar.

Example from my ec2:

![Screenshot from 2021-02-14 10-46-12](https://user-images.githubusercontent.com/362176/107881344-f397a300-6eb1-11eb-8d21-be948e2d6f66.png)

**Comment by kevinquillen** [comment]
I had to figure all of this out also, there is almost no documentation around this and something I am trying to change. You will find some example cfgs for running server games in the README on this project.

**Comment by icebird28** [comment]
Is there a way to play it without using the server version?

**Comment by kevinquillen** [comment]
Yes, you can put the meta directory like above in your Quake directory. Change your Quake executable to have the flags '-game meta' and it will start the game with those files loaded. From there, you can start a local multiplayer game and be discoverable via LAN or share your IP. I have not tried that with nquake itself, only with Quake 1 on Steam. The process is the same regardless, whatever app starts the Quake game, you need to add those arguments to it.

Once in the game that way, you can issue commands in the Quake console, like 'map e2m2' to change the map or other admin commands.
